# Generated by Django 4.1 on 2022-09-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
