# Generated by Django 4.1 on 2022-09-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wabi', '0003_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='wabi.prompt'),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='wabi.user'),
        ),
    ]
