# Generated by Django 4.1 on 2022-09-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wabi', '0004_alter_sketch_prompt_alter_sketch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='wabi.user')),
                ('users', models.ManyToManyField(to='wabi.user')),
            ],
        ),
    ]
