# Generated by Django 4.1 on 2022-09-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabi', '0005_remove_user_friends_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='wabi.user'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
